version: "3"

services: 
  data-service:
      image: appv0.0.1:latest
      volumes:
        - ./data-service:/usr/src/app
      ports:
        - 5002:8080
      depends_on: 
        - mongodb
  mongodb:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - data:/data/db
volumes: 
  data:
  
      
